# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               rzsun
url:                 "https://rzsun.dev"
paginate:            100
baseurl:             ""
markdown:            kramdown


# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
sass_dir:           _sass
style:              :compressed

# About/contact
author:             RZ Sun
name:              
url:                
email:              

# Custom vars
version:             
github:
repo:               https://github.com/rzsun

plugins:
  - jekyll-paginate
  - jekyll-sitemap